"""Cria as tabelas iniciais

Revision ID: 46dd538461aa
Revises: 480d41bf3fc2
Create Date: 2025-11-19 19:07:15.625400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46dd538461aa'
down_revision: Union[str, Sequence[str], None] = '480d41bf3fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('corridas', 'id_motorista',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('corridas', 'id_veiculo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('corridas', 'id_servidor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('corridas', 'valor',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('corridas', 'tempo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('corridas', 'distancia',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('motoristas', 'localizacao_atual',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('motoristas', 'id_veiculo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('motoristas', 'id_servidor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('motoristas', 'id_servidor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('motoristas', 'id_veiculo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('motoristas', 'localizacao_atual',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('corridas', 'distancia',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('corridas', 'tempo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('corridas', 'valor',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('corridas', 'id_servidor',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('corridas', 'id_veiculo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('corridas', 'id_motorista',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
