"""Cria as tabelas iniciais

Revision ID: 480d41bf3fc2
Revises: dc1fcbcdb78a
Create Date: 2025-11-16 17:19:59.676711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480d41bf3fc2'
down_revision: Union[str, Sequence[str], None] = 'dc1fcbcdb78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
