"""Cria as tabelas iniciais

Revision ID: 929513a189f3
Revises: 
Create Date: 2025-11-12 19:53:37.976811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929513a189f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passageiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_passageiros_email'), 'passageiros', ['email'], unique=True)
    op.create_index(op.f('ix_passageiros_id'), 'passageiros', ['id'], unique=False)
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=100), nullable=False),
    sa.Column('uptime', sa.Integer(), nullable=False),
    sa.Column('is_coordenador', sa.Boolean(), nullable=False),
    sa.Column('ultimo_heartbeat', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_servidores_id'), 'servidores', ['id'], unique=False)
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_table('motoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('localizacao_atual', sa.String(length=255), nullable=False),
    sa.Column('id_veiculo', sa.Integer(), nullable=False),
    sa.Column('id_servidor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servidor'], ['servidores.id'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('telefone')
    )
    op.create_index(op.f('ix_motoristas_email'), 'motoristas', ['email'], unique=True)
    op.create_index(op.f('ix_motoristas_id'), 'motoristas', ['id'], unique=False)
    op.create_table('corridas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_motorista', sa.Integer(), nullable=False),
    sa.Column('id_passageiro', sa.Integer(), nullable=False),
    sa.Column('id_veiculo', sa.Integer(), nullable=False),
    sa.Column('id_servidor', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=255), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('distancia', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_motorista'], ['motoristas.id'], ),
    sa.ForeignKeyConstraint(['id_passageiro'], ['passageiros.id'], ),
    sa.ForeignKeyConstraint(['id_servidor'], ['servidores.id'], ),
    sa.ForeignKeyConstraint(['id_veiculo'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridas_id'), 'corridas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corridas_id'), table_name='corridas')
    op.drop_table('corridas')
    op.drop_index(op.f('ix_motoristas_id'), table_name='motoristas')
    op.drop_index(op.f('ix_motoristas_email'), table_name='motoristas')
    op.drop_table('motoristas')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_servidores_id'), table_name='servidores')
    op.drop_table('servidores')
    op.drop_index(op.f('ix_passageiros_id'), table_name='passageiros')
    op.drop_index(op.f('ix_passageiros_email'), table_name='passageiros')
    op.drop_table('passageiros')
    # ### end Alembic commands ###
