[project]
name = "corridas-distribuidas-api"
version = "0.1.0"
description = "API para o projeto de corridas distribuidas, referente ao trabalho final da disciplina de sistemas distribuidos"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.1",
    "fastapi[standard]>=0.112.1",
    "httptools>=0.6.1",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.44",
]
