version: "3.9"
services:
  master:
    build: .
    command: python master.py
    environment:
      - SYNC_INTERVAL=10   # sincroniza a cada 10s
    depends_on:
      - worker1
      - worker2

  worker1:
    build: .
    container_name: worker1
    environment:
      - OFFSET=-5   # 5 segundos atrasado
    command: python worker.py

  worker2:
    build: .
    container_name: worker2
    environment:
      - OFFSET=+7   # 7 segundos adiantado
    command: python worker.py
